### ISSUE TITLE
RSR P2/2 Investigar de ciclos python

### ISSUE THREAD

**Issue by renesolis** [PFLC/py301#2]
# Encontre el codigo del ciclo de python

**Comment by KMCL** [comment]
Holaa

**Comment by miguelbianquiz** [comment]
Estoy nervioso

**Comment by renesolis** [comment]
# Como ven esta herramienta ? Project Manager
 @PFLC/301

**Comment by renesolis** [comment]
a
![300px-dia_0 95_flowchart](https://cloud.githubusercontent.com/assets/9355728/20606879/d1fd21b0-b228-11e6-9d02-ef3c0dc46e27.png)
